<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class AndroidSMS_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
	
	function GetSMSToBeSendList()
	{
		return $this->db->get_where("wp_ars_SMSGatewaySendSms",array("issent"=>0))->result();
	}
	function UpdateSentSMS($id)
	{
		$this->db->where("ID",$id);
		$this->db->update("wp_ars_SMSGatewaySendSms",array("issent"=>1));
	}
	
}