<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Imageupload_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get product by ProductId
     */
    function get_product($ProductId)
    {
        return $this->db->get_where('product',array('ProductId'=>$ProductId))->row_array();
    }
    
    /*
     * Get all product count
     */
    function get_all_product_count()
    {
        $this->db->from('product');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all product
     */
    function get_all_product($params = array())
    {
        $this->db->order_by('ProductId', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('product')->result_array();
    }
        
    /*
     * function to add new product
     */
    function add_product($params)
    {
        $this->db->insert('product',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update product
     */
    function update_product($ProductId,$params)
    {
        $this->db->where('ProductId',$ProductId);
        return $this->db->update('product',$params);
    }
    
    /*
     * function to delete product
     */
    function delete_product($ProductId)
    {
        return $this->db->delete('product',array('ProductId'=>$ProductId));
    }
}
