<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class OrderStatus_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get order by OrderId
     */
    function get_order_status_processing()
    {
		$this->db->where("orderstatus","Processing");
		return $this->db->get("orderstatus")->row();
	}
	
	function get_order_status_name($orderStatusId)
    {
		$this->db->where("orderstatusid",$orderStatusId);
		$result =  $this->db->get("orderstatus")->row();
		
		if($result)
		{
			return $result->OrderStatus;
		}
		
		return "";
	}
    
	
	function get_all_order_status()
	{
		return $this->db->get("orderstatus")->result();
	}
	
	function get_order_status_by_count()
	{
		return $this->db->query("select *,(select count(*) from orders o where o.IsDelete=0 and o.OrderStatusId=os.OrderStatusId)as OrderStatusCount from orderstatus os ")->result();
	}
	
    /*
     * Get all orders count
     */
    function get_all_orders_count()
    {
		$this->db->where('isdelete',0);
        $this->db->from('orders');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all orders
     */
    function get_all_orders($params = array())
    {        
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
		
		return $this->db->query("select o.OrderId,o.OrderStatus,o.CreatedDate as OrderDate,p.ProductName,concat(c.FirstName,' ',c.LastName) as CustomerName, (o.CODAmount+o.ShippingCost) as TotalCOD,
c.Cell1,c.Cell2,c.ShippingAddress,c.City
from Orders o 
join product p on o.ProductId=p.ProductId
join customer c on o.customerid = c.CustomerId
where o.isdelete=0
order by o.OrderId desc
")->result_array();
		
        
    }
        
    /*
     * function to add new order
     */
    function add_order($params)
    {
        $this->db->insert('orders',$params);
        return $this->db->insert_id();
    }
    
    
    
    /*
     * function to delete order
     */
    function delete_order($OrderId)
    {
		
		$this->db->where('OrderId',$OrderId);
        return $this->db->update('orders',array("isdelete"=>1));
		
    }
	
	function get_orderstatus_list($fromDate,$toDate,$orderStatusId,$city)
	{
		
		return $this->db->query("select o.OrderId,os.OrderStatus,o.OrderNotes,o.CreatedDate as OrderDate,p.ProductName,concat(c.FirstName,' ',c.LastName) as CustomerName, (o.CODAmount+o.ShippingCost) as TotalCOD,
c.Cell1,c.Cell2,c.ShippingAddress,c.City
from Orders o 
join OrderStatus os on o.OrderStatusId = os.OrderStatusId
join product p on o.ProductId=p.ProductId
join customer c on o.customerid = c.CustomerId
where o.isdelete=0
and c.City='".$city."'
and os.OrderStatusId=".$orderStatusId."
and cast(o.CreatedDate as date)>='".$fromDate."'
and cast(o.CreatedDate as date)<='".$toDate."'
order by o.OrderId desc")->result_array();
	}
}
