<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tcsexcel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
		
    }
    
    function get_data()
	{
		return $this->db->query("select concat(c.FirstName,' ',c.LastName,'(',c.cell2,')') as `Consignee Name`,
		concat(c.ShippingAddress,'(','Famous Place:',c.NearMostFamousPlace,')') as `Consignee Address`,
		c.cell1 as `Consignee Mobile Number`, c.email as `Consignee Email`, 
		c.city as `Destination City`,'1' as `Pieces`,'0.5' as `Weight`,(o.CODAmount+o.ShippingCost) as `COD Amount`,concat('bkey-',o.OrderId) as `Customer Reference Number`,
		'Yes' as `Special Handling`,
		'O' as `Service Type`,
		concat(p.productname,' ',o.ProductVariation) as `Product Details`,
		'Please Call Before Delivery' as `Remarks`		
		from orders o 
		join orderstatus os on o.OrderStatusId = os.OrderStatusId
		join product p on o.ProductId=p.ProductId
		join customer c on o.customerid = c.CustomerId
		where o.isdelete=0
		and os.OrderStatus='Tcs Confirm'		
		");
		
		
		
	}
	
	
}
