<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class TCSpayment_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
		
    }
    
    function add_delivery($param)
	{
		if(!$this->db->query("select * from tcspayment where CNNumber='".$param["CNNumber"]."' ")->row())
		{
			$id=$this->db->insert("tcspayment",$param);
			if($id)
			{
				return TRUE;
				
			}
		}
		return FALSE;
	}
	
	function add_payment($param)
	{
		$this->db->where("CNNumber",$param["CNNumber"]);
		unset($param["CNNumber"]);
		
		
		$this->db->update("tcspayment",$param);
		if($this->db->affected_rows()==1)
		{
			return TRUE;
		}
		return FALSE;
	
	}
	
	
	function GetPaymentDetail($param)
	{
		if($param["filter"]=="unpaid")
		{
			$this->db->where("CODAmount",0);
		}
		if($param["filter"]=="complete")
		{
			$this->db->where("CODAmount>",0);
			$this->db->where("ShippingCharges>",0);
		}
		
		if($param["fromDate"] && $param["toDate"])
		{
			$this->db->where("BookingDate>=",$param["fromDate"]);
			$this->db->where("BookingDate<=",$param["toDate"]);
		}
		
		if($param["deliveryStatus"])
		{
			$this->db->where("DeliveryStatus",$param["deliveryStatus"]);
		}
		
		if($param["sort"]=="BookingDateAsc")
		{
				$this->db->order_by("BookingDate","asc");
		}
		else if($param["sort"]=="BookingDateDesc")
		{
			$this->db->order_by("BookingDate","desc");
		}
		
		return $this->db->get("tcspayment")->result();
	}
}
