<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contactus extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		IsLogin();
        $this->load->model('Contactus_model');
    }
	
	function index()
	{
		$data["allData"]=$this->Contactus_model->get_all();
		$data['_view'] = 'admin/contactus/index';
        $this->load->view('admin/layouts/main',$data);
	}
}
