<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Productcat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		IsLogin();
        $this->load->model('admin/Productcat_model');
    } 

    /*
     * Listing of productcat
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('productcat/index?');
        $config['total_rows'] = $this->Productcat_model->get_all_productcat_count();
        $this->pagination->initialize($config);

        $data['productcat'] = $this->Productcat_model->get_all_productcat($params);
        
        $data['_view'] = 'admin/productcat/index';
        $this->load->view('admin/layouts/main',$data);
    }

    /*
     * Adding a new productcat
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('CatName','CatName','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'CatName' => $this->input->post('CatName'),
            );
            
            $productcat_id = $this->Productcat_model->add_productcat($params);
            redirect('admin/productcat/index');
        }
        else
        {            
            $data['_view'] = 'admin/productcat/add';
            $this->load->view('admin/layouts/main',$data);
        }
    }  

    /*
     * Editing a productcat
     */
    function edit($ProductCatId)
    {   
        // check if the productcat exists before trying to edit it
        $data['productcat'] = $this->Productcat_model->get_productcat($ProductCatId);
        
        if(isset($data['productcat']['ProductCatId']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('CatName','CatName','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'CatName' => $this->input->post('CatName'),
                );

                $this->Productcat_model->update_productcat($ProductCatId,$params);            
                redirect('admin/productcat/index');
            }
            else
            {
                $data['_view'] = 'admin/productcat/edit';
                $this->load->view('admin/layouts/main',$data);
            }
        }
        else
            show_error('The productcat you are trying to edit does not exist.');
    } 

    /*
     * Deleting productcat
     */
    function remove($ProductCatId)
    {
        $productcat = $this->Productcat_model->get_productcat($ProductCatId);

        // check if the productcat exists before trying to delete it
        if(isset($productcat['ProductCatId']))
        {
            $this->Productcat_model->delete_productcat($ProductCatId);
            redirect('productcat/index');
        }
        else
            show_error('The productcat you are trying to delete does not exist.');
    }
    
}
